#!/bin/bash
sudo systemctl stop postgresql
sudo systemctl disable postgresql
sudo pacman -Rns postgresql
sudo rm -rf /var/lib/postgres
sudo rm -rf /etc/postgresql
sudo userdel -r postgres
sudo find / -name '*postgresql*' -exec rm -rf {} \;
sudo pacman -Rns $(pacman -Qtdq)
sudo rm -rf /var/lib/postgres/data
sudo rm -rf /usr/share/locale/ka/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/ka/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/ka/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/ko/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/ko/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/ko/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/ko/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/ko/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/ko/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/ko/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/nb/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/pl/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/pl/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/pl/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/pl/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/pl/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/pl/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/pl/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/pt_BR/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/pt_BR/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/pt_BR/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/pt_BR/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/pt_BR/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/pt_BR/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/pt_BR/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/ro/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/ru/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/ru/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/ru/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/ru/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/ru/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/ru/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/ru/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/sv/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/sv/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/sv/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/sv/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/sv/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/sv/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/sv/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/ta/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/tr/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/tr/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/tr/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/tr/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/tr/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/tr/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/tr/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/uk/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/uk/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/uk/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/uk/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/uk/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/uk/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/uk/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/vi/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/vi/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/vi/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/zh_CN/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/zh_CN/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/zh_CN/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/zh_CN/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/zh_CN/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/zh_CN/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/zh_CN/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/zh_TW/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/zh_TW/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/zh_TW/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/zh_TW/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/zh_TW/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/zh_TW/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/man/man1/clusterdb.1.gz
sudo rm -rf /usr/share/man/man1/createdb.1.gz
sudo rm -rf /usr/share/man/man1/createuser.1.gz
sudo rm -rf /usr/share/man/man1/dropdb.1.gz
sudo rm -rf /usr/share/man/man1/dropuser.1.gz
sudo rm -rf /usr/share/man/man1/pg_config.1.gz
sudo rm -rf /usr/share/man/man1/pg_dump.1.gz
sudo rm -rf /usr/share/man/man1/pg_dumpall.1.gz
sudo rm -rf /usr/share/man/man1/pg_isready.1.gz
sudo rm -rf /usr/share/man/man1/pg_restore.1.gz
sudo rm -rf /usr/share/man/man1/psql.1.gz
sudo rm -rf /usr/share/man/man1/reindexdb.1.gz
sudo rm -rf /usr/share/man/man1/vacuumdb.1.gz
sudo rm -rf /usr/bin/clusterdb
sudo rm -rf /usr/bin/createdb
sudo rm -rf /usr/bin/createuser
sudo rm -rf /usr/bin/dropdb
sudo rm -rf /usr/bin/dropuser
sudo rm -rf /usr/bin/ecpg
sudo rm -rf /usr/bin/pg_config
sudo rm -rf /usr/bin/pg_dump
sudo rm -rf /usr/bin/pg_dumpall
sudo rm -rf /usr/bin/pg_isready
sudo rm -rf /usr/bin/pg_restore
sudo rm -rf /usr/bin/psql
sudo rm -rf /usr/bin/reindexdb
sudo rm -rf /usr/bin/vacuumdb
sudo rm -rf /usr/include/ecpg_config.h
sudo rm -rf /usr/include/ecpg_informix.h
sudo rm -rf /usr/include/ecpgerrno.h
sudo rm -rf /usr/include/ecpglib.h
sudo rm -rf /usr/include/ecpgtype.h
sudo rm -rf /usr/include/libpq-events.h
sudo rm -rf /usr/include/libpq-fe.h
sudo rm -rf /usr/include/libpq/libpq-fs.h
sudo rm -rf /usr/include/pg_config.h
sudo rm -rf /usr/include/pg_config_ext.h
sudo rm -rf /usr/include/pg_config_manual.h
sudo rm -rf /usr/include/pg_config_os.h
sudo rm -rf /usr/include/pgtypes.h
sudo rm -rf /usr/include/pgtypes_date.h
sudo rm -rf /usr/include/pgtypes_error.h
sudo rm -rf /usr/include/pgtypes_interval.h
sudo rm -rf /usr/include/pgtypes_numeric.h
sudo rm -rf /usr/include/pgtypes_timestamp.h
sudo rm -rf /usr/include/postgres_ext.h
sudo rm -rf /usr/include/sql3types.h
sudo rm -rf /usr/include/sqlca.h
sudo rm -rf /usr/include/sqlda-compat.h
sudo rm -rf /usr/include/sqlda-native.h
sudo rm -rf /usr/include/sqlda.h
sudo rm -rf /usr/lib/libecpg.so
sudo rm -rf /usr/lib/libecpg.so.6
sudo rm -rf /usr/lib/libecpg.so.6.16
sudo rm -rf /usr/lib/libecpg_compat.so
sudo rm -rf /usr/lib/libecpg_compat.so.3
sudo rm -rf /usr/lib/libecpg_compat.so.3.16
sudo rm -rf /usr/lib/libpgtypes.so
sudo rm -rf /usr/lib/libpgtypes.so.3
sudo rm -rf /usr/lib/libpgtypes.so.3.16
sudo rm -rf /usr/lib/libpq.so
sudo rm -rf /usr/lib/libpq.so.5
sudo rm -rf /usr/lib/libpq.so.5.16
sudo rm -rf /usr/lib/pkgconfig/libecpg.pc
sudo rm -rf /usr/lib/pkgconfig/libecpg_compat.pc
sudo rm -rf /usr/lib/pkgconfig/libpgtypes.pc
sudo rm -rf /usr/lib/pkgconfig/libpq.pc
sudo rm -rf /usr/share/locale/cs/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/cs/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/cs/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/cs/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/cs/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/cs/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/cs/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/de/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/de/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/de/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/de/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/de/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/de/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/de/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/el/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/el/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/el/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/el/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/el/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/el/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/el/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/es/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/es/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/es/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/es/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/es/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/es/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/es/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/fr/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/fr/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/fr/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/fr/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/fr/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/fr/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/fr/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/he/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/he/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/he/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/he/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/he/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/it/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/it/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/it/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/it/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/it/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/it/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/it/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/ja/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/ja/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/ja/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/ja/LC_MESSAGES/pg_config-16.mo
sudo rm -rf /usr/share/locale/ja/LC_MESSAGES/pg_dump-16.mo
sudo rm -rf /usr/share/locale/ja/LC_MESSAGES/pgscripts-16.mo
sudo rm -rf /usr/share/locale/ja/LC_MESSAGES/psql-16.mo
sudo rm -rf /usr/share/locale/ka/LC_MESSAGES/ecpg-16.mo
sudo rm -rf /usr/share/locale/ka/LC_MESSAGES/ecpglib6-16.mo
sudo rm -rf /usr/share/locale/ka/LC_MESSAGES/libpq5-16.mo
sudo rm -rf /usr/share/locale/ka/LC_MESSAGES/pg_config-16.mo
